// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pmp-question-bank/Dashboard.tsx": () => import("../components/mockups/pmp-question-bank/Dashboard.tsx"),
  "./components/mockups/pmp-question-bank/PracticeSetup.tsx": () => import("../components/mockups/pmp-question-bank/PracticeSetup.tsx"),
  "./components/mockups/pmp-question-bank/Question.tsx": () => import("../components/mockups/pmp-question-bank/Question.tsx"),
  "./components/mockups/pmp-question-bank/Results.tsx": () => import("../components/mockups/pmp-question-bank/Results.tsx")
};
